---
version: "3.8"
services:
  movies:
    image: pavitragayam/paytmmovies:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  recharge:
    image: pavitragayam/paytmrecharge:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: pavitragayam/paytmdth:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
